<html>

<head>
<meta http-equiv="Content-Language" content="es">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>:: Estudio Aduanero Dávila :: Comercio Exterior ::</title>

<SCRIPT LANGUAGE="JavaScript">

<!-- Free JavaScript Rollover Buttons from -->
<!-- http://www.creatupropiaweb.com -->

<!-- Begin

image1 = new Image();
image1.src = "images/b1_2.jpg";

image2 = new Image();
image2.src = "images/b2_2.jpg";

image3 = new Image();
image3.src = "images/b3_2.jpg";

image4 = new Image();
image4.src = "images/b4_2.jpg";

image5 = new Image();
image5.src = "images/b5_2.jpg";

image6 = new Image();
image6.src = "images/b6_2.jpg";

image7 = new Image();
image7.src = "images/b7_2.jpg";

// End -->
</script>



<style type="text/css">
.auto-style1 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: small;
}
.auto-style2 {
	border-width: 0px;
}
</style>



</head>

<body bgcolor="#000000">

<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="800" height="501">
    <tr>
      <td height="31" background="images/bg1.jpg">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100%" height="126">
          <tr>
            <td width="12%" height="126" valign="top">
            
            <a onmouseover="image1.src='images/b1_2.jpg';" onmouseout="image1.src='images/b1_1.jpg';" href="home.ASP">
<img name="image1" src="images/b1_1.jpg" border=0></a>

            
</td>
            <td width="12%" height="126" valign="top"><a href="historia.ASP" onmouseover="image2.src='images/b2_2.jpg';"
onmouseout="image2.src='images/b2_1.jpg';">
<img name="image2" src="images/b2_1.jpg" border=0></a></td>


            <td width="12%" height="126" valign="top"><a href="descargas.ASP" onmouseover="image3.src='images/b3_2.jpg';"
onmouseout="image3.src='images/b3_1.jpg';">
<img name="image3" src="images/b3_1.jpg" border=0></a></td>

            <td width="12%" height="126" valign="top"><a href="legislacion.asp" onmouseover="image4.src='images/b4_2.jpg';"
onmouseout="image4.src='images/b4_1.jpg';">
<img name="image4" src="images/b4_1.jpg" border=0></a></td>


            <td width="13%" height="126" valign="top"><a href="novedades.asp" onmouseover="image5.src='images/b5_2.jpg';"
onmouseout="image5.src='images/b5_1.jpg';">
<img name="image5" src="images/b5_1.jpg" border=0></a></td>

            <td width="13%" height="126" valign="top"><a href="contacto.asp" onmouseover="image6.src='images/b6_2.jpg';"
onmouseout="image6.src='images/b6_1.jpg';">
<img name="image6" src="images/b6_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><a href="privado.asp" onmouseover="image7.src='images/b7_2.jpg';"
onmouseout="image7.src='images/b7_1.jpg';">
<img name="image7" src="images/b7_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><img border="0" src="images/logo.jpg"></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="141" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" height="99" width="95%">
          <tr>
            <td height="99" width="735">
            <img border="0" src="images/sevice.jpg" align="right" hspace="15" vspace="10"><p>&nbsp;</p>
            <p><img border="0" src="images/Servicios.gif"> </p>
			<p class="auto-style1"><strong>Descarga de documentos</strong></p>
            <p><img border="0" src="images/img05a.gif"></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            A continuación encontrará documentos de interés para descargar a su 
			computadora. Haga clik sobre el documento de su interés con el botón 
			derecho y elija &quot;Guardar como&quot;.
            </span></font></p>
            <p>&nbsp;</td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="16" bgcolor="#FFFFFF" background="images/bg3.jpg">&nbsp;</td>
    </tr>
    <tr>
      <td height="294" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="10" cellspacing="10" style="border-collapse: collapse" width="100%" height="336">
          <tr>
            <td height="306">
            <p align="center" class="auto-style1">
			<a href="descargas/BITMurno.pdf">
			<img class="auto-style2" height="36" src="images/icono_pdf.gif" width="37"></a>&nbsp;
			<a href="descargas/BITMurno.pdf">Valoración en Aduana de 
			Exportaciones</a></p>
			<p align="center"><span class="auto-style1">
			<a href="descargas/Expo%20x%20cta%20terceros%20CDA%20-%20Fundamentos%20Presentacion%20MZA%20Mayo%202013%20Mendoza.pdf">
			<img class="auto-style2" height="36" src="images/icono_pdf.gif" width="37"></a>&nbsp;
			<a href="descargas/Expo%20x%20cta%20terceros%20CDA%20-%20Fundamentos%20Presentacion%20MZA%20Mayo%202013%20Mendoza.pdf">
			Exportación por cuenta y orden de terceros,</a></span><a href="descargas/Expo%20x%20cta%20terceros%20CDA%20-%20Fundamentos%20Presentacion%20MZA%20Mayo%202013%20Mendoza.pdf"><br class="auto-style1">
			<span class="auto-style1">Herramienta para exportadores. Y ahora 
			para importadores</span></a></p>
			<p align="center"><img border="0" src="images/img05a.gif"></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Póngase en <b><a href="contacto.ASP"><font color="#006666">contacto</font></a></b> con nosotros y pondremos a su disposición toda 
            nuestra experiencia y know how. Puede hacerlo utilizando el 
            <b><a href="contacto.ASP"><font color="#006666">formulario de contacto</font></a></b> o cualquiera de las vías de contacto que 
            desee.</span></font></p>
			<p align="center"><a href="Newsletter.asp">
      <img border="0" src="images/newssmall.jpg" width="234" height="52"></a></p>
            <p align="center"><img border="0" src="images/img06a.gif"></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="19" bgcolor="#006666">
      <p align="center"><span lang="es"><!-- Histats.com  START  -->
<a href="http://www.histats.com/es/" target="_blank" title="contador pagina web" ><script  type="text/javascript" language="javascript">
var s_sid = 657888;var st_dominio = 4;
var cimg = 152;var cwi =85;var che =17;
      </script></a>
<script  type="text/javascript" language="javascript" src="http://s11.histats.com/js9.js"></script>
<noscript>
      <a href="http://www.histats.com/es/" target="_blank">
<img  src="http://s103.histats.com/stats/0.gif?657888&1" alt="contador pagina web" border="0"></a></noscript>
<!-- Histats.com  END  --></span></td>
    </tr>
  </table>
  </center>
</div>

<p align="center">&nbsp;</p>

</body>

</html>