
<%
  %>
<html>

<head>
<meta http-equiv="Content-Language" content="es">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>:: Estudio Aduanero Dávila :: Comercio Exterior ::</title>

<SCRIPT LANGUAGE="JavaScript">

<!-- Free JavaScript Rollover Buttons from -->
<!-- http://www.creatupropiaweb.com -->

<!-- Begin

image1 = new Image();
image1.src = "images/b1_2.jpg";

image2 = new Image();
image2.src = "images/b2_2.jpg";

image3 = new Image();
image3.src = "images/b3_2.jpg";

image4 = new Image();
image4.src = "images/b4_2.jpg";

image5 = new Image();
image5.src = "images/b5_2.jpg";

image6 = new Image();
image6.src = "images/b6_2.jpg";

image7 = new Image();
image7.src = "images/b7_2.jpg";

// End -->
</script>



</head>

<body bgcolor="#000000">




<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="800" height="501">
    <tr>
      <td height="31" background="images/bg1.jpg">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100%" height="126">
          <tr>
            <td width="12%" height="126" valign="top">
            
            <a onmouseover="image1.src='images/b1_2.jpg';" onmouseout="image1.src='images/b1_1.jpg';" href="home.ASP">
<img name="image1" src="images/b1_1.jpg" border=0></a>

            
</td>
            <td width="12%" height="126" valign="top">
            <a onmouseover="image2.src='images/b2_2.jpg';" onmouseout="image2.src='images/b2_1.jpg';" href="historia.ASP">
<img name="image2" src="images/b2_1.jpg" border=0></a></td>


            <td width="12%" height="126" valign="top">
            <a onmouseover="image3.src='images/b3_2.jpg';" onmouseout="image3.src='images/b3_1.jpg';" href="servicios.ASP">
<img name="image3" src="images/b3_1.jpg" border=0></a></td>

            <td width="12%" height="126" valign="top"><a href="legislacion.asp" onmouseover="image4.src='images/b4_2.jpg';"
onmouseout="image4.src='images/b4_1.jpg';">
<img name="image4" src="images/b4_1.jpg" border=0></a></td>


            <td width="13%" height="126" valign="top"><a href="novedades.asp" onmouseover="image5.src='images/b5_2.jpg';"
onmouseout="image5.src='images/b5_1.jpg';">
<img name="image5" src="images/b5_1.jpg" border=0></a></td>

            <td width="13%" height="126" valign="top">
            <a onmouseover="image6.src='images/b6_2.jpg';" onmouseout="image6.src='images/b6_1.jpg';" href="contacto.ASP">
<img name="image6" src="images/b6_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><a href="privado.asp" onmouseover="image7.src='images/b7_2.jpg';"
onmouseout="image7.src='images/b7_1.jpg';">
<img name="image7" src="images/b7_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><img border="0" src="images/logo.jpg"></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="141" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" height="99" width="730">
          <tr>
            <td height="99">
            <img border="0" src="images/compu.jpg" align="right" hspace="20" vspace="5"><p>&nbsp;</p>
            <p><img border="0" src="images/gracias.gif"></p>
            <p><img border="0" src="images/img05a.gif"></p>
            <p>&nbsp;</p>
            <p align="center"><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Su mensaje ha sido enviado <b><font color="#006666">con éxito </font>
            </b>!</span></font></p>
            <p align="center"><a href="Newsletter.asp">
      <img border="0" src="images/newssmall.jpg" width="234" height="52"></a></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="16" bgcolor="#FFFFFF" background="images/bg3.jpg">&nbsp;</td>
    </tr>
    <tr>
      <td height="294" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="10" cellspacing="10" style="border-collapse: collapse" width="668" height="336">
          <tr>
            <td height="13" width="628">
            <p align="center">
            <img border="0" src="images/oficina-2.jpg" align="left" hspace="15" vspace="15"></p>
            <p align="center">
            &nbsp;</p>
            <p align="center">
            <img border="0" src="images/img05a.gif"></p>
            <p align="center">
            &nbsp;</p>
            <p align="center">
            <img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Muy pronto <b><font color="#006666">nos comunicaremos</font></b> con 
            usted.
            </span></font></p>
            <p align="center">
            <img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es">
            </span></font><span lang="es"><font face="Verdana" size="2">E</font></span><font face="Verdana" size="2"><span lang="es">l 
            staff de Estudio Dávila ya está <b><font color="#006666">trabajando</font></b> 
            en su requerimiento.</span></font></p>
            <p align="center">
            &nbsp;</p>
            <p align="center">
            <img border="0" src="images/img05a.gif"></p>
            <p align="center">
            &nbsp;</p>
            <p align="center">
            <img border="0" src="images/img06a.gif"></p>
            <p align="center">
            <font color="#006666" size="2" face="Verdana"><span lang="es">¿ Ha 
            leído las <b><a href="novedades.asp"><font color="#006666">últimas 
            novedades </font></a></b>?</span></font></p>
            <p align="center">
            <img border="0" src="images/img06a.gif"></p>
            </td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="19" bgcolor="#006666">
      <p align="center"><span lang="es"><!-- Histats.com  START  -->
<a href="http://www.histats.com/es/" target="_blank" title="contador pagina web" ><script  type="text/javascript" language="javascript">
var s_sid = 657888;var st_dominio = 4;
var cimg = 152;var cwi =85;var che =17;
      </script></a>
<script  type="text/javascript" language="javascript" src="http://s11.histats.com/js9.js"></script>
<noscript>
      <a href="http://www.histats.com/es/" target="_blank">
<img  src="http://s103.histats.com/stats/0.gif?657888&1" alt="contador pagina web" border="0"></a></noscript>
<!-- Histats.com  END  --></span></td>
    </tr>
  </table>
  </center>
</div>

<p align="center">&nbsp;</p>

</body>

</html>