<html>

<head>
<meta http-equiv="Content-Language" content="es">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>:: Estudio Aduanero Dávila :: Comercio Exterior ::</title>

<SCRIPT LANGUAGE="JavaScript">

<!-- Free JavaScript Rollover Buttons from -->
<!-- http://www.creatupropiaweb.com -->

<!-- Begin

image1 = new Image();
image1.src = "images/b1_2.jpg";

image2 = new Image();
image2.src = "images/b2_2.jpg";

image3 = new Image();
image3.src = "images/b3_2.jpg";

image4 = new Image();
image4.src = "images/b4_2.jpg";

image5 = new Image();
image5.src = "images/b5_2.jpg";

image6 = new Image();
image6.src = "images/b6_2.jpg";

image7 = new Image();
image7.src = "images/b7_2.jpg";

// End -->
</script>



</head>

<body bgcolor="#000000">

<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="800" height="501">
    <tr>
      <td height="31" background="images/bg1.jpg">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100%" height="126">
          <tr>
            <td width="12%" height="126" valign="top">
            
            <a onmouseover="image1.src='images/b1_2.jpg';" onmouseout="image1.src='images/b1_1.jpg';" href="home.ASP">
<img name="image1" src="images/b1_1.jpg" border=0></a>

            
</td>
            <td width="12%" height="126" valign="top"><a href="historia.asp" onmouseover="image2.src='images/b2_2.jpg';"
onmouseout="image2.src='images/b2_1.jpg';">
<img name="image2" src="images/b2_1.jpg" border=0></a></td>


            <td width="12%" height="126" valign="top"><a href="servicios.asp" onmouseover="image3.src='images/b3_2.jpg';"
onmouseout="image3.src='images/b3_1.jpg';">
<img name="image3" src="images/b3_1.jpg" border=0></a></td>

            <td width="12%" height="126" valign="top"><a href="legislacion.asp" onmouseover="image4.src='images/b4_2.jpg';"
onmouseout="image4.src='images/b4_1.jpg';">
<img name="image4" src="images/b4_1.jpg" border=0></a></td>


            <td width="13%" height="126" valign="top"><a href="novedades.asp" onmouseover="image5.src='images/b5_2.jpg';"
onmouseout="image5.src='images/b5_1.jpg';">
<img name="image5" src="images/b5_1.jpg" border=0></a></td>

            <td width="13%" height="126" valign="top"><a href="contacto.asp" onmouseover="image6.src='images/b6_2.jpg';"
onmouseout="image6.src='images/b6_1.jpg';">
<img name="image6" src="images/b6_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><a href="privado.asp" onmouseover="image7.src='images/b7_2.jpg';"
onmouseout="image7.src='images/b7_1.jpg';">
<img name="image7" src="images/b7_1.jpg" border=0></a></td>
            
            <td width="13%" height="126" valign="top"><img border="0" src="images/logo.jpg"></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="141" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" height="99" width="95%">
          <tr>
            <td height="99" width="735"><p><span lang="es"><font size="2" face="Verdana">
            <img border="0" src="images/DonLuisDavila.jpg" align="right" width="185" height="246" hspace="50"></font></span></p>
            <p><span lang="es"><font size="2" face="Verdana">
            <img border="0" src="images/Historia.gif"></font></span></p>
            <p><img border="0" src="images/img05a.gif"></p>
            <p>&nbsp;</p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es">
            </span></font><span lang="es"><font size="2" face="Verdana">Empresa 
            fundada por Don Luis Jorge Dávila en su juventud. </font></span></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es">
            </span></font><span lang="es"><font size="2" face="Verdana">Por más 
            de 58 años trabajando en forma ininterrumpida </font></span>
            <p><span lang="es"><font face="Verdana" size="2">&nbsp; para las empresas de 
            la región y el país.</font></span></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="16" bgcolor="#FFFFFF" background="images/bg3.jpg">&nbsp;</td>
    </tr>
    <tr>
      <td height="294" bgcolor="#FFFFFF">
      <div align="center">
        <center>
        <table border="0" cellpadding="10" cellspacing="10" style="border-collapse: collapse" width="100%" height="336">
          <tr>
            <td height="306">
            <img border="0" src="images/DonLuisDavila_2.jpg" align="left" hspace="10" vspace="3"><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Actualmente la segunda generación de la familia es quien está a 
            cargo de la empresa. Las hijas de Don Luis, Silvana Dávila, 
            Despachante de Aduana y Lucía Dávila, continúan con el legado de su 
            padre, atendiendo a las necesidades de los importadores y 
            exportadores, principalmente del <b><font color="#006666">mercado Vitivinícola</font></b>.</span></font><p align="center">
            <img border="0" src="images/img05a.gif"></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Una sólida trayectoria en el mercado provincial, nacional e 
            internacional, son avalados por las empresas que confían en el 
            conocimiento de las operativas aduaneras de <b>
            <font color="#006666">exportación e 
            importación</font></b>, y por otro lado la dedicación personalizada de los 
            integrantes del staff de la empresa, contribuyen a que los clientes 
            puedan alcanzar con éxito sus objetivos comerciales.</span></font></p>
            <p align="center"><img border="0" src="images/img05a.gif"><font face="Verdana" size="2"><span lang="es"><img border="0" src="images/oficina.jpg" align="right" hspace="15" vspace="7"></span></font></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Actualmente <b><font color="#006666">Estudio Dávil</font></b>a, además de contar con la asistencia y 
            experiencia de Don Luis Jorge y sus hijas, también está integrado 
            por personal administrativo y dependientes en Puerto Seco (Mendoza) 
            y en todos los lugares donde las necesidades operativas lo 
            requieren. También el Estudio cuenta con la última tecnología en 
            software para la tramitación y aprobación de todas las 
            destinaciones, como el <b><font color="#006666">Sistema María </font>
            </b>y <b><font color="#006666">Mymtec</font></b>.</span></font></p>
            <p align="center"><img border="0" src="images/img05a.gif"></p>
            <p><img border="0" src="images/Flecha-der2.jpg"><font face="Verdana" size="2"><span lang="es"> 
            Póngase en <b><a href="contacto.ASP"><font color="#006666">contacto</font></a></b> con nosotros y pondremos a su disposición toda 
            nuestra experiencia y know how. Puede hacerlo utilizando el 
            <b><a href="contacto.ASP"><font color="#006666">formulario de contacto</font></a></b> o cualquiera de las vías de contacto que 
            desee.</span></font></p>
			<p align="center"><a href="Newsletter.asp">
      <img border="0" src="images/newssmall.jpg" width="234" height="52"></a></p>
            <p align="center"><img border="0" src="images/img06a.gif"></td>
          </tr>
        </table>
        </center>
      </div>
      </td>
    </tr>
    <tr>
      <td height="19" bgcolor="#006666">
      <p align="center"><span lang="es"><!-- Histats.com  START  -->
<a href="http://www.histats.com/es/" target="_blank" title="contador pagina web" ><script  type="text/javascript" language="javascript">
var s_sid = 657888;var st_dominio = 4;
var cimg = 152;var cwi =85;var che =17;
      </script></a>
<script  type="text/javascript" language="javascript" src="http://s11.histats.com/js9.js"></script>
<noscript>
      <a href="http://www.histats.com/es/" target="_blank">
<img  src="http://s103.histats.com/stats/0.gif?657888&1" alt="contador pagina web" border="0"></a></noscript>
<!-- Histats.com  END  --></span></td>
    </tr>
  </table>
  </center>
</div>

<p align="center">&nbsp;</p>

</body>

</html>